spring:
  application:
    name: kubernetes-config
microservice-base:
  kubernetes:
    config:
      config-maps:
        - name: configmap-example-01
logging:
  level:
    com.freemanan.kubernetes.config: debug
fm:
  pricing:
    price: 100
