apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-example-01
  namespace: default
data:
  pricing.yml: |
    fm:
      pricing:
        price: 199
    logging:
      level:
        com.freemanan.example.controller: info
