apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-config
  namespace: default
spec:
  selector:
    matchLabels:
      app: kubernetes-config
  template:
    metadata:
      labels:
        app: kubernetes-config
    spec:
      containers:
        - name: kubernetes-config
          image: kubernetes-config:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-config
  namespace: default
spec:
  selector:
    app: kubernetes-config
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort