server:
  port: 10000
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: api
          uri: http://api-gateway:9999
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
        - id: web
          uri: http://web:8080
          predicates:
            - Path=/**
