server:
  port: 10000
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: api
          uri: http://localhost:9999 # api-gateway
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
#        - id: web
#          uri: http://localhost:80
#          predicates:
#            - Path=/**
