server:
  port: 9999
  error:
    include-message: always
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user
          uri: http://localhost:8081
          predicates:
            - Path=/v*/user/**, /internal/v*/user/**
        - id: pet
          uri: http://localhost:8082
          predicates:
            - Path=/v*/pet/**, /internal/v*/pet/**
microservice-base:
  kubernetes:
    grey:
      grey-gateway:
        authority: localhost:8080
