apiVersion: v1
kind: ConfigMap
metadata:
  name: grey
  namespace: default
data:
  grey.yml: |
    microservice-base:
      kubernetes:
        grey:
          rules:
            - name: rule-01
              predicates:
                headers:
                  - name: grey-name
                    pattern: rule-01
              mappings:
                - master:
                    service: localhost
                    namespace: default
                    port: 8000
                  features:
                    - service: localhost
                      port: 8001
                      weight: 10
                    - service: localhost
                      namespace: default
                      port: 8002
                      weight: 10               
